### PR TITLE
Significant restructuring of running path with Main as the start.  Al…

### PR DESCRIPTION
**Pull request by Togira**
…so added lecture initializer information to the Lecture class and other minor adjustments.

### CODE REVIEW

**Comment by Togira** [comment]
@pranaygp @NavneethJayendran Both of you need to sign off before we merge this one. I recommend running Main to see what is going on.  No significant functionality was added but the run path was reformatted.  Now it's much easier (in my opinion) to see where print messages are coming from and the order of execution.

**Comment by NavneethJayendran** [comment]
As long as it compiles, I concur with the changes.

As for changing Lecture.toString(), it's ultimately a testing/debug method, so change it whenever convenient.

In the spirit of OO, we might also want to eventually turn LectureInitializer into a non-static class that can be instantiated and that contains a Roster as well as a list of Lectures. I feel it would make our design hierarchy compact and mostly complete like:
LectureAnalyzer{
    Lectures{
        FeedbackEntries
    }
    Roster{
        Students{
            FeedbackEntries
        }
    }
    NRList{
        NetIDPairs
    }
}
and the changes you've made (eg moving Lecture.get(FeedbackEntry) to LectureInitializer.get(FeedbackEntry) move us in this direction.

**Comment by NavneethJayendran** [comment]
Well that could have gotten formatted better... at least the curly braces preserve the intent. @pranaygp to review and merge.

**Comment by pranaygp** [comment]
@Togira :+1: for taking this up

**Pull request merged**
