### PR TITLE
Implement Iterable for NRList and Lecture and other changes

### PR DESCRIPTION
**Pull request by NavneethJayendran**
Fixed various compile errors existing with my old code and finished what I had started. Properly implemented Iterable interface for NRList and Lecture. Added resize method for Roster. Modified NetIDPair to make its netID field invisible (as it should be). Added merge constructor for FeedbackEntry.

### CODE REVIEW

**Comment by pranaygp** [comment]
@NavneethJayendran I can't approve these changes till:
 1. You respond to my message on Slack.
 2. You fix merge conflicts.

 > You need to be on the `Compile-error-corrections` branch, and then do a `git merge develop`
 3. You submit the answer to life, the universe and everything else as a comment to PR #11 


@Togira I think he was unaware of the work we were doing since he didn't bother following our messages on Slack and Github PRs/Issues. However, he's made more significant changes that do more than Compiling Error Corrections. Hence, I'm gonna rename this but PR #13 is something that is still essential.

**Comment by pranaygp** [comment]
@NavneethJayendran WTF are you doing?

**Comment by NavneethJayendran** [comment]
I'm really not sure. I resolved the conflict by deleting your branch but didn't know how to present that for approval... or however this works. Sorry, I'm not used to command lines at all. I'll study how to use Git before making any more changes. Did I merge in the wrong direction?

**Comment by NavneethJayendran** [comment]
So tell me where I should have stopped (or if this is even remotely right)
$Notepad Roster.java //Remove conflicts
$git add Roster.java 
$git commit
$git push

**Comment by pranaygp** [comment]
The steps before this. You were in develop and pulled in your branch.
You shouldve been in your branch, and puklled in changes from develop.

Read my comment above

**Comment by NavneethJayendran** [comment]
Oh I see. Is the command for that just
$checkout Compiler-error-corrections
? I thought I tried that and failed at changing branches. Or I might be remembering wrong. At any rate, sorry about this. If there's anything disagreeable about these changes, we can revert the merge. The largest changes are to NetIDPair (now prevents access to the netID field), FeedbackEntry (has merge constructor), and Roster (supports resizing). I also properly implemented Iterable for Lecture and NRList. The rest are name changes and reformatting code to fit 80 columns.

**Comment by pranaygp** [comment]
Yeah, that's the right command, but sometimes git can be a bitch to work with. Especially with merge issues. 

It should be alright, but yup, I'd suggest reading up on git tutorial. Both basic and advanced.

A bit of git goes a long way.

**Comment by Togira** [comment]
Actually, these changes look great!  Merge conflicts are just a pain in general.  Nice work!

PS I made a new branch for bug-fixes and I think we should focus on getting lecture initializer to run properly on that branch before making any new branches off of develop.  Let me know what you guys think.  I'll be hopefully adding the missing roster file shortly.

**Pull request merged**
