### PR TITLE
added a .gitignore file and applied the changes

### PR DESCRIPTION
**Pull request by Togira**
@pranaygp 
@NavneethJayendran 
Please comment when you have approved this merge. I simply added a basic .gitignore file that looks like this and applied the changes.  Last time, I merged in the map-proposal pr before which caused merge conflicts.  So I created a new branch off develop to make the .gitignore file and apply the changes again.  This should be merged before any other branches/pr are made off of develop.

+# Compiled source #
+###################
+.com
+.class
+.dll
+.exe
+.o
+.so
+
+# Mobile Tools for Java (J2ME)
+.mtj.tmp/
+
+# Package Files #
+.jar
+.war
+.ear
+
+# OS generated files #
+######################
+.DS_Store
+.DS_Store?
+._
+.Spotlight-V100
+.Trashes
+ehthumbs.db
+Thumbs.db

I am by no means an expert on .gitignore files so if this looks fishy to you, then please let me know.

### CODE REVIEW

**Comment by Togira** [comment]
Again, here is a reference for what I did: http://stackoverflow.com/questions/19663093/apply-gitignore-on-an-existing-repository-already-tracking-large-number-of-files

**Comment by pranaygp** [comment]
Your pr shows that `.DS_Store` is still getting tracked. Is that supposed to happen?

If so, this is good...
Else, might wanna fix that before the merge

**Comment by Togira** [comment]
I added ".DS_Store" to the .gitignore already so I'm not sure where you see that getting tracked.  In my commit, .DS_Store is being removed. Perhaps that's what you are referring to?

**Comment by NavneethJayendran** [comment]
I'm even less of an expert... so I'll assume this works. Feel free to merge.

**Comment by Togira** [comment]
I'll let @pranaygp hit the button.

**Pull request merged**
