### PR TITLE
Large work on FeedbackEntry, small elsewhere

### PR DESCRIPTION
**Pull request by NavneethJayendran**
Most of the changes are to FeedbackEntry. Check the commit messages and notes for more info. But the gist of it is that I added a FeedbackEntry(String) constructor for testing purposes and overhauled splitCommas(String) and checkCorruptData(String) to properly handle (and better explain the problems with) corrupt data. 

In other news, I properly replaced all instances of Lecture.getValues() to Lecture.ratingDistribution(). Let me know if anyone disagrees with this change. 

I also added a Roster(int) constructor for testing purposes.

### CODE REVIEW

**Comment by pranaygp** [comment]
@NavneethJayendran regarding the file in Slack about `ENCODEDpeerInteractions` (I'm posting this here because I'm not sure if you read Slack often.

How did you manage to run into issues with that file. It isnt being used anywhere in the codebase. It was a redundant file that I simply pasted in the directory for future reference. You mentioned that it cause the program to crash though, which makes no sense to me.

Either way, The changes in this pull request look good so, Approved.

@Togira need you to confirm/merge this

**Comment by NavneethJayendran** [comment]
Oh. That's a bit confusing... there's an encoded normal version in src and an encoded ENCODED version in root. Sorry about that. Fortunately that accident served as a good test case to reveal the flaws of our error handling. I would also recommend deleting that file if it has no purpose.

**Comment by pranaygp** [comment]
Yup, that's true.

Sorry about the discrepency.

feel free to push a commit that deletes it.

I'm currently undergoing a "Documents" folder cleanup on my PC and can't do anything for a bit.

**Comment by Togira** [comment]
This looks awesome @NavneethJayendran  thanks for all the hard work!  After updating CleanFeedbackData to use the new FeedbackEntry constructor and a relative file path to the peer interactions data, lecture initializer runs as expected :).

**Pull request merged**
